
export const UPDATE_NOMINATION_LIST = 'UPDATE_NOMINATION_LIST';

export const NOMINATE_MOVIES_SUCCESS = 'NOMINATE_MOVIES_SUCCESS';

export const NOMINATE_MOVIES_FAIL = 'NOMINATE_MOVIES_FAIL';

export const FETCH_NOMINATION_SUCCESS = 'FETCH_NOMINATION_SUCCESS';

export const AUTH_START = 'AUTH_START';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';

export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';







